version: 'LTS'
networks:
  jenkins-network:
    name: jenkins
volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs
services:
  jenkins:
    container_name: jenkins-marvin
    image: jenkins/jenkins
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 8080:8080
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
